-- ARCHIVED - do not run this file.
--
-- This was the original bootstrap script from before the app had real
-- Supabase Auth. Back then kv_store had a single "allow all access" policy
-- (see the comment that used to be here: "the app has its own name+password
-- login built in, not Supabase Auth, so we allow the public anon key to
-- read/write this table freely").
--
-- That is no longer true. A later security migration added real Supabase
-- Auth (see signInMember/setMemberPasswordAndSignIn in src/storage.js),
-- replaced the "allow all" kv_store policy with role-aware RLS policies
-- (authenticated required for writes, several keys further restricted to
-- admins/owner/team leads), and added RLS + column-level grants to every
-- other table in the project. The actual schema, policies, and grants now
-- live only in the Supabase project itself (Dashboard -> Database), not in
-- this repo - there is no up-to-date migration file to run from scratch.
